### ISSUE TITLE
A method to scrape all Forvo pronunciations

### ISSUE THREAD

**Issue by ghost** [justunsix/french-learning-ms#2]
A method to scrape all Forvo pronunciations is now available:

https://ankiweb.net/shared/info/858591644#:~:text=a%20method%20to%20scrape%20all

You can choose your target Language. Works really well !

**Comment by justunsix** [comment]
@FyTpodQUuWvQNTh Thank you for sharing the Anki add on! 

I will look into [its Python code](https://github.com/realmayus/anki_forvo_dl/tree/main/src) to see if it can be adapted to HTML/JS. 

For anyone using Anki as their flashcard and wants to pull the Forvo pronunciations, the add on looks great.

**Comment by ghost** [comment]
Your idea of Multisearch is good but using GoldenDict is 10x faster. You can look in many French Dictionaries simultaneously and have the pronunciation also simultaneously. Everything offline :

![image](https://user-images.githubusercontent.com/58692066/142787977-3d794fb1-bb88-48ea-b149-0f4d6cee77c5.png)

You could download the "Early Release version" of GoldenDict and download French Dictionaries here on FreeMDict:

https://downloads.freemdict.com/100G_Super_Big_Collection/%E6%B3%95%E8%AF%AD/

Also visit:  https://forum.freemdict.com/

If you use Anki, those .mdx dictionaries can be used with the add-on called "Fast word query" : 
https://ankiweb.net/shared/info/1807206748

**Comment by ghost** [comment]
All Forvo audios are now available to download:

https://forum.freemdict.com/t/topic/11947

You can use them for your language learning :D
